name: distance_classification
batch_size: 32
# limit: 5          # Optional: Limit number of samples to evaluate
# suffix_tag: dev   # Optional: Custom suffix for the output directory
kwargs:
  scheme: 3-group
