name: source_classification
batch_size: 256
# limit: 5          # Optional: Limit number of samples to evaluate
# suffix_tag: dev   # Optional: Custom suffix for the output directory
kwargs:
  active_classes:
    GALAXY: Galaxy
    QSO: Quasar
