name: subclass_classification
batch_size: 32
# limit: 5          # Optional: Limit number of samples to evaluate
# suffix_tag: dev   # Optional: Custom suffix for the output directory
kwargs:
  active_classes:
    AGN: AGN
    STARBURST: Starburst
    STARFORMING: Starforming
    BROADLINE: Broadline
